### ISSUE TITLE
Load ipython code as module

### ISSUE THREAD

**Issue by waynebliu** [deathbeds/importnb#106]
I want to load plain files with ipython as modules, rather than using %load.  Importnb seems to require ipynb notebooks. Can it import non-notebook files also? Thanks.

**Comment by tonyfast** [comment]
not yet, but we can make this happen, feels like an oversight not having this. thanks @waynebliu

**Comment by waynebliu** [comment]
Awesome! Actually it's more an oversight of ipython to not have this, but you're correcting that.

**Comment by tonyfast** [comment]
i think this #110 will resolve this issue. it will be in the 0.7.0 release i'll try to ship next week.

**Comment by waynebliu** [comment]
Hi @tonyfast are you planning to do the 0.7.0 release?  Would love to start using this feature. :)

**Comment by tonyfast** [comment]
@waynebliu wecut a release for you!  :pray:  thanks for keeping us honest. we'd love to see some of the ways you are using `importnb` if you are open to sharing with us.

**Comment by waynebliu** [comment]
Great, thank you tonyfast! 
At work we automate a lot of our developer workflow using notebooks - basically any how-to wiki is written as a notebook.  I like to use ipython instead of bash for writing utility functions for notebooks and I use importnb to share and import utils 'properly'. Otherwise it's too hard to share them.

**Comment by bollwyvl** [comment]
👌 thanks for sharing!
