### ISSUE TITLE
Import only definitions, classes while avoiding other statements

### ISSUE THREAD

**Issue by davidleejy** [deathbeds/importnb#116]
Is it possible to do the equivalent of `import ipynb.fs.defs.notebook123` in importnb? This imports only definitions in `notebook123.ipynb` and avoids other statements. For e.g. if there's a statement `foo='hi'` in `notebook123.ipynb`, it does not get imported.

I think this is a useful feature since there might be executable statements in `notebook123.ipynb` that demonstrate how the functions work and are kept uncommented in the notebook for debugging and communicative purposes. Would be neat if these statements aren't imported.

**Comment by tonyfast** [comment]
this feature is added by #127 . it will be important to note the caveat that global variables cant be used in local scopes when this behavior is activated.

**Comment by jeroenvuurens** [comment]
This does not work anymore?

**Comment by tonyfast** [comment]
seems to work for me when i use the `include_non_defs=False`.

my example notebook has a print statement that should display when `include_non_defs` is True:

![image](https://github.com/deathbeds/importnb/assets/4236275/f92d46dd-8946-46bf-96fa-3e0d0fbc21b0)


the following cells show loading with this style behavior.

![image](https://github.com/deathbeds/importnb/assets/4236275/fc1d680f-2856-41dc-b182-e914c4ffe344)
