### ISSUE TITLE
[Feature Request] Ignore cell magics

### ISSUE THREAD

**Issue by davidleejy** [deathbeds/importnb#119]
Importing a .ipynb containing cell magic (statements prefixed with %) into a .py file raises an exception; the cell magic isn't recognized. No errors are raised when importing *into* a .ipynb file.

**Comment by tonyfast** [comment]
thanks for this feature request. i'm going to work on implementing this soon.

this feature fits `importnb` because there is pure python that doesn't require `IPython`. since magics require `IPython` we'll add this feature as work around.
