### ISSUE TITLE
managing, versioning, licensing of lark grammars

### ISSUE THREAD

**Issue by bollwyvl** [deathbeds/importnb#123]
It looks like the [checked-in version](https://github.com/deathbeds/importnb/commit/fd1cf2e872a8061460cac433b1646303b3c8b844#diff-52c3753c52ab94f45352d9d0940688d3e39a80d28d34314e0a621343f90d2378R2) was built with `0.12.0`, but the current version is `1.1.2` (and the tests pass). It's probably worth building with (at least) `1.1.x`.

If indeed the grammar becomes pluggable, e.g. `with Notebook(parser_cls=Some_Other_Lark)` which might enable #119 or other options, it would be good to know which versions of lark were compatible... this is straying into `tox` territory... or just delegating to being in the CI matrix. 

Further, generated grammars are covered by the [MPL](https://github.com/deathbeds/importnb/commit/fd1cf2e872a8061460cac433b1646303b3c8b844#diff-52c3753c52ab94f45352d9d0940688d3e39a80d28d34314e0a621343f90d2378R14). I don't know about the compatibility of that with BSD-3. It might  be simplest to change the main license (which is fine) or distribute as a separate package (which is also fine).

**Comment by tonyfast** [comment]
closed by #129
