### ISSUE TITLE
add `MPL-2.0` license file for generated lark grammar

### ISSUE THREAD

**Issue by tonyfast** [deathbeds/importnb#149]

**Comment by bollwyvl** [comment]
A bit of clarification: I haven't looked at the `lark` license discussion in a while: https://github.com/lark-parser/lark/issues/1255

At least one user said 

> But simply using the generator doesn't sublicence the result since it's a mechanical process, not a person.

Without being jumped on and corrected.

_If_ the final product _is_ governed by `MPL-2.0`, to dot all the `i`s, the [`license` field](https://hatch.pypa.io/1.7/config/metadata/#license) would probably be like:

```
license = "BSD-3-Clause AND MPL-2.0"
```

As to the contents of the files, likely just pasting the full text at the bottom after a little preamble.

```
The JSON grammar was built using the lark standalone tool, which is licensed under the Mozilla Public License 2.0:

  # ... text of license 
```

Or maybe the `license-files` might be something like:

```
license-files = { paths = ["LICENSE", "grammar/LICENSE"] }
```

Or maybe the compiled grammar ends up in a whole separate installable package (bleah), but still cut from this repo. More licenses more problems.
