### ISSUE TITLE
Notebook review tool

### ISSUE THREAD

**Issue by smith-kyle** [deathbeds/importnb#157]
I'm just discovering deathbeds and I'm excited to use `importnb` for future features. Always excited to see people building on the notebook ecosystem. 

I noticed you all aren't using a notebook review tool and just wanted to suggest GitNotebooks. Your latest pull request can be viewed here: https://gitnotebooks.com/deathbeds/importnb/pull/143

Keep up the good work!

**Comment by bollwyvl** [comment]
Thanks, good luck.
