### ISSUE TITLE
importnb Not Working on Jupyter Lab

### ISSUE THREAD

**Issue by gioarma** [deathbeds/importnb#93]
Hi I'm new to python and jupyter notebooks and I am trying to use this module to import a ipynb file in another ipynb file. I installed it with conda and I am running it on Jupyter Lab.
I tried to follow your readme but I have problems understanding it and I cannot even get started. In notebook 'A.ipynb' I tried to run:
```python
from importnb import Notebook
Notebook.from_filename('*FULL_PATH*/B.ipynb')
```
I get the error: 

`type object 'Notebook' has no attribute 'from_filename'`.

I also tried with `Notebook.load('*FULL_PATH*/B.ipynb')` and this time I don't get any error, but when I call a test function written in B.ipynb from A.ipynb I get an error because the function is not defined. 
What am I missing? 
Thank you

**Comment by bollwyvl** [comment]
That may be a typo/change in the docs vs an older version. Try

    nb = Notebook().from_filename(...)
    nb.test_function() # should work

**Comment by gioarma** [comment]
No luck, I still get the error `'Notebook' object has no attribute 'from_filename'`

**Comment by bollwyvl** [comment]
Looks like it's just `Notebook.load`, which is part of the test suite. Most
of the readme _is_ part of the test suite, but those references were only
in markdown code blocks. Sorry for the inconvenience!

I was just able to try out `load` on binder, looks fine with an absolute
path.

We'll update the docs to reflect this: I think the new form is better:
shorter, more like what stdlib would do (no doubt it's inheriting that
behavior). Cc @tonyfast

**Comment by gioarma** [comment]
Ok thanks!
I summerize for anyone who might have this problem. What works is:
```python
from importnb import Notebook
nb = Notebook().load('*FULL_PATH*/B.ipynb')
```
Then to call the function `test()` within B.ipynb the code is: `nb.test()`
